### PR TITLE
Fix ruby 2.7 warning

### LINKED ISSUE #221: Ruby 2.6 warning (__FILE__ in eval)
See related issue in Pry: https://github.com/pry/pry/issues/1871, https://github.com/pry/pry/pull/1904 (not released yet)

When running Ruby 2.6 in verbose mode, it shows this warning:

```
env RUBYOPT="-w" bundle exec pry 
<main>:1: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
[1] pry(main)> 
```

```ruby
gem "pry", git: "https://github.com/pry/pry", ref: "69f7d9d185726abc4a84b3731f1735f501a81266"
gem "pry-byebug", "3.7.0"
```

If I remove pry-byebug gem, the warning disappears.

Culprits:

https://github.com/deivid-rodriguez/pry-byebug/blob/master/lib/pry-byebug/base.rb#L16

https://github.com/deivid-rodriguez/pry-byebug/blob/master/lib/pry-byebug/helpers/breakpoints.rb#L23

(BTW, running "pry" from master completely breaks with pry-byebug, but that's a separate issue.)

### PR DESCRIPTION
**Pull request by whois-marvin-42**
Fixed warning raised by latest ruby (__FILE__ in eval) in base.rb

Fixes #221.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Ruby 2.7 is released, these warnings are annoying.

**Comment by deivid-rodriguez** [comment]
Right, I'll try to get a new version out today :+1:.

**Comment by AlexWayfer** [comment]
Probably, we can take out common code with condition… into private method, for example. Or public class method, if it between different classes. Right now there is a duplication of logic.

File: lib/pry-byebug/helpers/location.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    #
+    module Location
+      module_function
+
+      #
+      # Current file in the target binding. Used as the default breakpoint
+      # location.
+      #
+      def current_file(source = target)
+        return source.source_location[0] if source.respond_to?(:source_location)
```
Comment (AlexWayfer) [inline lib/pry-byebug/helpers/location.rb]: Here is could be a comment about Ruby versions, warnings.

Also, the `source_location` is since Ruby 1.9 or earlier, and `pry-byebug` has Ruby 2.3 as minimal, so… I think we're not needing in `eval("__FILE__")` at all.

If so — we can just replace the code, even without Helper, I guess.

Comment (whois-marvin-42) [reply lib/pry-byebug/helpers/location.rb]: You're right ! Since `source_location` is available in Ruby's versions above minimal requirements, I agree, there is no need for eval or a helper at all

**Comment by whois-marvin-42** [comment]
CI showed problems for Ruby < 2.6 (missing `source_location`) ... rolled back to working proposal.

**Comment by AlexWayfer** [comment]
> CI showed problems for Ruby < 2.6 (missing `source_location`) ... rolled back to working proposal.

Oh, it's `Binding#source_location`, introduced in Ruby 2.6, and I saw `Method#source_location`… sorry, my bad.

File: lib/pry-byebug/helpers/location.rb (hunk 1 above)
Comment (AlexWayfer) [reply lib/pry-byebug/helpers/location.rb]: We've faced with unavailability `Binding#source_location` in Ruby < 2.6. I think, here is still can be a comment about this.

**Comment by whois-marvin-42** [comment]
My bad too, I should have double-checked before making modifications.

File: lib/pry-byebug/helpers/location.rb (hunk 1 above)
Comment (whois-marvin-42) [reply lib/pry-byebug/helpers/location.rb]: Added comment

**Comment by whois-marvin-42** [comment]
Don't know what deivid-rodriguez had in mind ... just hoping it helps. AlexWayfer, thanks for your point of view.

**Comment by AlexWayfer** [comment]
> Don't know what deivid-rodriguez had in mind ... just hoping it helps. AlexWayfer, thanks for your point of view.

Everything is OK when CI passes. :ok_hand:

**Comment by deivid-rodriguez** [comment]
It's looking good to me. Could you rebase and add a changelog entry?

**Comment by AlexWayfer** [comment]
> and add a changelog entry?

It'd be nice to add a note about this in `CONTRIBUTING.md`.

**Comment by whois-marvin-42** [comment]
Done. Hope it's what you were expecting. Thanks for this tool btw.

**Comment by deivid-rodriguez** [comment]
Thanks so much @whois-marvin-42!

**Comment by deivid-rodriguez** [comment]
> It'd be nice to add a note about this in CONTRIBUTING.md.

Sure @AlexWayfer, can you open a PR?

**Comment by AlexWayfer** [comment]
> > It'd be nice to add a note about this in CONTRIBUTING.md.
> 
> Sure @AlexWayfer, can you open a PR?

Maybe, but it's your requirement, maybe you have others, so, I think, it's better to do you, as Owner (maintainer). For example, I prefer to update Changelog before releases.

**Comment by deivid-rodriguez** [comment]
Sure, I'll do it myself.

**Comment by deivid-rodriguez** [comment]
When I said, "I'll try to get a new version out today", that was way too optimistic :sweat_smile:. I'll do it during next week though.

**Comment by MarcusRiemer** [comment]
Any chance for a version bump?

**Comment by deivid-rodriguez** [comment]
I'll be releasing 3.8.0 in a bit. One question though, is this warning 2.7.0 specific? Because I can't reproduce it on MRI 2.6.

**Comment by AlexWayfer** [comment]
> One question though, is this warning 2.7.0 specific?

Yep.

**Comment by deivid-rodriguez** [comment]
Thanks! I'll clarify this in the changelog!

**Comment by tisba** [comment]
I'm not sure why, but I see this warning, when I updated to Ruby 2.7.1 using pry-byebug 3.9.0:

```
gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
```

**Comment by deivid-rodriguez** [comment]
I'm not sure why. Can you show the full backtrace?

**Comment by tisba** [comment]
Sure. What's the simplest way to get the full backtrace for warnings? 🤔

**Comment by tisba** [comment]
Ah, I missed the next line. Looks like it caused by `pry-stack_explorer` gem:

```
/home/smith/vendor/bundle/ruby/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
/home/smith/vendor/bundle/ruby/2.7.0/gems/pry-stack_explorer-0.4.9.3/lib/pry-stack_explorer/when_started_hook.rb:63: warning: in `eval'
```

Do I read this correctly?

**Comment by deivid-rodriguez** [comment]
Yeah, `pry-stack_explorer` needs to be updated. Specifically this line: https://github.com/pry/pry-stack_explorer/blob/02d18dceb7178ebbdc52673532afb85c1f8b51d8/lib/pry-stack_explorer/when_started_hook.rb#L63.

**Comment by tisba** [comment]
duh, I believe there is already an issue for this https://github.com/pry/pry-stack_explorer/issues/43

Sorry for the noise here :)

**Comment by deivid-rodriguez** [comment]
No problem!
